# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8yH62uqmdaBl8k6rjwofK5zduN7GAhv
"""

!pip install streamlit>=1.30.0

!pip install pandas>=2.0.0

!pip install numpy>=1.24.0

!pip install matplotlib>=3.7.0

!pip install scikit-learn>=1.3.0

!pip install statsmodels>=0.14.0

!pip install openpyxl>=3.1.0